parserOptions:
  ecmaVersion: "latest"
  sourceType: "module"
env:
  es2022: true
  browser: true
  jquery: true
  node: true
extends: eslint:recommended
plugins:
  - html
globals:
  module: "writable"
  AblePlayer: "writable"
  $: "writable"
  jQuery: "writable"
  Cookies: "readonly"
rules:
  complexity: ["warn", { max: 10 }]
  no-unused-vars: "off"
  no-empty: "off"
  no-extra-boolean-cast: "off"
  no-redeclare: "off"
  no-constant-condition: "off"
  no-prototype-builtins: "off"
